"""empty message

Revision ID: 40893cfb619a
Revises: 
Create Date: 2025-03-16 21:19:31.732074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40893cfb619a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_input', sa.JSON(), nullable=False),
    sa.Column('model_predictions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    # ### end Alembic commands ###
